Add deployment info for Divio Cloud
torchbox/wagtail-news-template pull request #31
Opened 2024-11-27 12:10 UTC by FinalAngel

This merge request adds information on how to deploy the template to Divio Cloud according to a discussion between Adam and Meagen. The resulting template works out of the box within our environment ☺️

2024-12-02 13:11 UTC, diab88 approved these changes

2024-12-03 16:14 UTC, vossisboss commented
Hey @FinalAngel! Thank you for submitting this. I was out for the Thanksgiving holiday for most of last week, so I'm just getting around to testing this. I went through your instructions to deploy a copy of this repository to Divio and unfortunately the deployment failed for me with the following error:

===== docker build =====

starting docker build
Operation Error: failed to parse Dockerfile: Syntax error - can't find = in "project_name". Must be of the form: name=value

Any ideas on what the issue might be?

I made a few small language suggestions as well. Please let me know if you have any questions.

2024-12-12 10:00 UTC, FinalAngel commented
@vossisboss, no worries, I also have been off for holidays 🙈 I made some amendments regarding the deployment to make it clear that you'd need a local setup following the "Getting Started" guide. You'll end up with a setup like this:
https://github.com/finalangel/wagtail-news-template-testing/

I sadly did not see your language suggestions in the PR, did you submit the review? 🙇‍♂️

2025-01-07 15:36 UTC, vossisboss commented
Hi @FinalAngel. I was also out for the holidays. Now  I'm back and ready to finish this off. I did submit a review, so I'm not sure why you wouldn't be able to see the language changes I suggested. Can you see them in the comment stream above?

I'll have a look at the other things you added as well right now.

2025-01-14 09:49 UTC, FinalAngel commented
@vossisboss I'm a bit baffled, this is how I see it right now:

<img width="1380" alt="image" src="https://github.com/user-attachments/assets/9f5b269f-9555-41d0-af72-6aa546f240e9" />

2025-01-14 16:05 UTC, vossisboss requested changes
Submitting the review again. Hopefully, it will take this time. Just some small language suggestions.

2025-01-14 16:06 UTC, vossisboss commented
@FinalAngel I re-submitted the review. Can you see it now? Not sure why it didn't take the first time but it was probably some button I missed on my end.

2025-01-16 09:23 UTC, FinalAngel commented on README.md
> +   From the "Environments" view, click the "**Deploy**" button. Once the deployment completes, access your site using the "Env URL" link.
thanks for the suggestion, pushed an update accordingly :)

2025-01-16 22:00 UTC, vossisboss commented
Thanks for the update @FinalAngel! I'm going to tag in @RealOrangeOne for the final review and merge since I don't think I have merge privileges on this repository yet.

2025-01-21 09:38 UTC, FinalAngel commented on README.md
> +   You need a [database](https://docs.divio.com/introduction/aldryn-django/django-05-database/) in order for the deployment to succeed. For a quick deployment, commit your local `db.sqlite3` database
Thanks for the feedback, I adapted the docs to include a proper setup 💪

2025-01-21 09:38 UTC, FinalAngel commented on README.md
> +4. **Deploy Your Application**
That is true, the standard template does this automatically, within the manual setup here you'd need to configure those manually, I amended this to the docs as well 🙇‍♂️

2025-01-22 12:16 UTC, RealOrangeOne commented on README.md
> +
```suggestion
   Divio automatically provide **Test** and **Live** environments. From the "Environments" view, click "**Deploy**" on the **Test** environment. Once the deployment completes, access your site using the "Env URL" link.

5. **Additional Configuration**
   Add a "Release command" within the **Settings** section with the value `python manage.py migrate` to run migrations automatically on every deployment. You can add additional commands as needed. The **Env Variables** section allows you to set variables such as `SECRET_KEY` for the test and live environments.
```

2025-01-22 12:16 UTC, RealOrangeOne commented on README.md
> +5. **Additional Configuration**
Question: What about media storage?

2025-01-27 21:47 UTC, vossisboss commented
Hi @FinalAngel and @RealOrangeOne, I'm just checking in to see what needs to be resolved still so that we can keep this moving. Jake, it looks like you had a few points about how the database is discussed as well as media storage?

Media storage may be something we want to address or note in the broader directions as needing additional configuration if the settings we provide in the Starter Kit don't address them.

2025-01-28 08:22 UTC, FinalAngel commented on README.md
> +4. **Deploy Your Application**
The main difference is that you need to att the "python manage.py migrate" to the release command section. The default template that we offer does that automatically.

2025-01-28 08:22 UTC, FinalAngel commented on README.md
> +[![Deploy to Divio](https://docs.divio.com/deploy-to-divio.svg)](https://control.divio.com/app/new/?template_url=https://github.com/divio/getting-started-with-wagtail/archive/refs/heads/main.zip)
what would be the question? 🤔

2025-01-28 15:46 UTC, RealOrangeOne commented on README.md
> +[![Deploy to Divio](https://docs.divio.com/deploy-to-divio.svg)](https://control.divio.com/app/new/?template_url=https://github.com/divio/getting-started-with-wagtail/archive/refs/heads/main.zip)
D'oh! I answered my own question, and must have clicked comment not delete!

2025-02-03 21:29 UTC, vossisboss commented on README.md
> +[![Deploy to Divio](https://docs.divio.com/deploy-to-divio.svg)](https://control.divio.com/app/new/?template_url=https://github.com/divio/getting-started-with-wagtail/archive/refs/heads/main.zip)
I think @RealOrangeOne is right about this @FinalAngel. But I also think that maybe the link should be to Divio's sign up page or dashboard so that people know they have to get an account to proceed. Would that work for both of you?

2025-02-03 21:30 UTC, vossisboss commented on README.md
> +   **Media Storage**: Divio provides [object storage](https://docs.divio.com/reference/work-media-storage/) to store user-uploaded files. You can configure this within your [`settings.py`](https://gi
Would be great to have an answer to this @FinalAngel so that we can make adjustments.

2025-02-03 21:32 UTC, vossisboss commented
I'd love to get the announcement of adding Divio to our line up scheduled soon @FinalAngel. If you have a chance to look at @RealOrangeOne's feedback this week, I'd appreciate it.

2025-02-04 09:11 UTC, mebdivio commented
I'll be taking over this and will review what needs to be adjusted in our documentation. I'll get back to you as soon as possible.

2025-02-04 15:10 UTC, vossisboss commented
Thanks for the update @mebdivio!

2025-02-04 20:00 UTC, mebdivio commented
You're welcome, @vossisboss! I have tested and updated the README file. Please let me know if any further changes are required.

2025-02-04 20:07 UTC, vossisboss commented on README.md
> +[![Deploy to Divio](https://docs.divio.com/deploy-to-divio.svg)](https://control.divio.com/app/new/?template_url=https://github.com/divio/getting-started-with-wagtail/archive/refs/heads/main.zip)
@mebdivio I think the link provided here leads people away from the Starter Kit and to a different template, so it might be confusing for people. Perhaps we should just link to the general Divio dashboard or login in the button?

2025-02-04 20:11 UTC, vossisboss commented
@RealOrangeOne I've re-addressed the potential confusion around the button with @mebdivio. Is there anything else you see that needs to be addressed?

2025-02-05 12:08 UTC, RealOrangeOne commented
I've resolved the outstanding comments to clean things up. I think all that's left is the button link and the need to modify settings for media storage.

2025-02-05 15:42 UTC, mebdivio commented
@RealOrangeOne: Is there any issue with the Divio button? It’s a standard across all our templates.

Regarding settings.py, I thought it was clearly indicated that the settings were meant for further application configurations. Thanks for pointing that out! I had copied the link from elsewhere and forgot to remove the line numbers.

2025-02-05 16:11 UTC, vossisboss commented
@mebdivio Please see the previous comments we've made. While it might be standard, it's also potentially confusing for users since it directs them away from this template to Divio's standard Wagtail template, which doesn't use the starter kit template that the people reading these instructions want to use.  The Divio standard Wagtail template uses a basic Wagtail start command instead and people will probably find that confusing. That's why I've suggested you consider using a link to the dashboard or the login page instead.

2025-02-05 16:45 UTC, mebdivio commented
Thanks for that clarification! The link did seem confusing. I’ve updated it accordingly, and I hope it’s clearer now. Let me know if you think any further improvements are needed.

2025-02-05 17:14 UTC, RealOrangeOne commented
The link seems to now link to the wrong CMS, and still sadly doesn't link to our template.

2025-02-05 17:16 UTC, RealOrangeOne commented on README.md
> +   For further application-specific configurations, update your [`settings.py`](https://github.com/divio/getting-started-with-wagtail/blob/main/mysite/settings/base.py) accordingly.
From my reading, the current application isn't actually compatible with Divio's media storage, since it uses differnet environment variables - could support be added to this template for them, rather than pointing people to modifying the template.

If the user needs to modify the template to make it work with the platform, it's not really a "supported" platform, it's just mentioned in the docs.

2025-02-06 08:40 UTC, mebdivio commented on README.md
> +   For further application-specific configurations, update your [`settings.py`](https://github.com/divio/getting-started-with-wagtail/blob/main/mysite/settings/base.py) accordingly.
Thank you for clarifying this! I’ve reviewed the discussion, and I noticed you mentioned:

"Are the `DEFAULT_*` environment variables automatically set by Divio? If so, I'm not opposed to adding native support for them to the template, given it's a graceful fallback."

I can confirm that yes, the `DEFAULT_*` environment variables are set by Divio. If adding native support for them to the template is an option, that would be greatly appreciated. Would this be a workable solution?

2025-02-06 09:52 UTC, RealOrangeOne commented on README.md
> +   For further application-specific configurations, update your [`settings.py`](https://github.com/divio/getting-started-with-wagtail/blob/main/mysite/settings/base.py) accordingly.
Yep adding native support for them sounds useful to me, so long as it doesn't interfere with the existing allowed variables.

2025-02-06 13:26 UTC, mebdivio commented on README.md
> +   For further application-specific configurations, update your [`settings.py`](https://github.com/divio/getting-started-with-wagtail/blob/main/mysite/settings/base.py) accordingly.
Glad to hear that! How would you like to proceed? Would you like us to propose the necessary updates to the template, or would you prefer to handle them on your end?

2025-02-06 14:27 UTC, RealOrangeOne commented on README.md
> +[![Deploy to Divio](https://docs.divio.com/deploy-to-divio.svg)](https://control.divio.com/app/new/?template_url=https://github.com/divio/getting-started-with-payload/archive/refs/heads/main.zip)
Issue: This appears to still be wrong
```suggestion
[![Deploy to Divio](https://docs.divio.com/deploy-to-divio.svg)](https://control.divio.com/app/new/?template_url=https://github.com/torchbox/wagtail-news-template/archive/refs/heads/main.zip)
```

2025-02-07 15:18 UTC, mebdivio commented
I have updated the template by adding DEFAULT_* env vars for Divio integration (no changes needed to settings.py for Media STORAGES). I hope this is workable for us to move forward. Thanks and look forward to your feedback. https://github.com/torchbox/wagtail-news-template/pull/37

2025-02-07 16:04 UTC, RealOrangeOne commented
Thanks! I don't think this PR can be merged until #37, since the support isn't there. Similarly, once it is, the mentions of modifying `settings.py` can be removed from this PR, too.

2025-02-07 22:19 UTC, vossisboss commented
@RealOrangeOne and @mebdivio, how critical do you feel adding this support is to including the deployment instructions? How long will it take to add this support?

If it's a relatively easy addition to the template, I would be open to us pausing adding the deployment instructions until it's done. But if this is going to take a while, would it be possible for us to release an initial set of instructions and then iterate on them?

I definitely want us to deliver a great user experience but also if it's mostly functional, I feel it would be more beneficial for us to give people the option to use it sooner even if it isn't perfect.

2025-02-10 09:24 UTC, mebverse commented
As I mentioned in the PR https://github.com/torchbox/wagtail-news-template/pull/37,: @RealOrangeOne "Would it be possible for you to apply the changes you're suggesting? That would also help streamline the back-and-forth. We're fine with it as long as it works as intended."

To update you — on our side, I believe everything is functioning well. The mention of `settings.py` can be completely removed from the PR, and the changes you’re recommending could be handled by you, Jake,  to avoid unnecessary back-and-forth.

Thanks, Jake and Meagan for all your support! I’m confident that, as Meagan pointed out, this implementation will deliver a great user experience. Let’s move forward with releasing this as soon as possible.

2025-02-17 16:05 UTC, merged